### ISSUE TITLE
How do I rename library functions?

### ISSUE THREAD

**Issue by StarrySai** [shuakabane/stelftools#1]
Yara parses the library function name, but where is the function address?
And how do I automatically rename recognized functions?
And When to test mips or arm?

**Comment by shuakabane** [comment]
Thanks you for reading we paper and ask question.

Answer of first question.
Yara command does'nt output match pattern address. 
However, yara-python can get the offset address from the beginning of the file
We are calculating the virtualaddress based on the offset address.

Answer of second question.
I'm sorry, but I didn't understand the meaning of your question.

Answer of third question.
We have already tested our proposed method on 10 different architecture, including ARM and MIPS, using Intel 80386.
We have checked that our proposed method is also effective in the identification of library function for architectures other than Intel 80386.

If you have any additional questions, please send them to my e-mail address instead of the issue.
shu.akabane141@gmail.com
